### Create a text on DB
POST http://localhost:8000/auth0/private/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjN1VF9USnRlUHVpWC1Vc2hMUHAwVSJ9.eyJpc3MiOiJodHRwczovL2Rldi1kOGJtdGhiOGl4NDI4dHdqLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJhdXRoMHw2N2U5YzE0NWZhYzFmM2QzZTQ5ZjBmYTciLCJhdWQiOlsiaHR0cHM6Ly9xdWlja3N0YXJ0cy9hcGkiLCJodHRwczovL2Rldi1kOGJtdGhiOGl4NDI4dHdqLnVzLmF1dGgwLmNvbS91c2VyaW5mbyJdLCJpYXQiOjE3NDMzNzc4NDgsImV4cCI6MTc0MzQ2NDI0OCwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBlbWFpbCIsImd0eSI6InBhc3N3b3JkIiwiYXpwIjoiRnJ1Y0dHem5QV3hGUm9obXVDaWlXbHZSVmpSaTRWeksifQ.RiAda8Co82l4oltk9BdCfnXh_l8ZGH_GBfwDAzVlttTnk1L3k7Jlv-u7AeqdduVxaAdPhLRDnk3WeV0f4Xc2LL_bWXZfUIJbMIq_7OeCJX8kB0py1b7o9-oZZSPegUIjGME9wxFRYkCjSTQcZxj0Ie7hX7iMzgkArXTrOyUdICVvliyoZ_fTGPeVQI1w5T7TPMKqO_rkgbtHUn9EJJvwfF6TyjKckoQLrRUwUbhnldLDmu0_Yvxt5GDTJpBRaG4i2L0P6Mc2nMklBmfhaA2Ah8BjXJBYyu5r_-NX4nBXlwZMpvo0FHOWfteijAhtBBDogAFohFDQASMKxtYcvcZW1A

{
  "text": "hola mundo"
}

### Agregation Enpoint

GET http://localhost:8000/auth0/public/

### Machine to machine token
GET http://localhost:8000/auth0/public/get_token/

### Get user  token
POST http://localhost:8000/auth0/public/get_user_token/
Content-Type: application/json

{
	"username":"example@mail.com",
	"password":"abcPASS123!"
}