POST http://localhost:8000/auth0/private/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjN1VF9USnRlUHVpWC1Vc2hMUHAwVSJ9.eyJpc3MiOiJodHRwczovL2Rldi1kOGJtdGhiOGl4NDI4dHdqLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJhdXRoMHw2N2U5YzE0NWZhYzFmM2QzZTQ5ZjBmYTciLCJhdWQiOlsiaHR0cHM6Ly9xdWlja3N0YXJ0cy9hcGkiLCJodHRwczovL2Rldi1kOGJtdGhiOGl4NDI4dHdqLnVzLmF1dGgwLmNvbS91c2VyaW5mbyJdLCJpYXQiOjE3NDMzNzQ3NDAsImV4cCI6MTc0MzQ2MTE0MCwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBlbWFpbCIsImd0eSI6InBhc3N3b3JkIiwiYXpwIjoiRnJ1Y0dHem5QV3hGUm9obXVDaWlXbHZSVmpSaTRWeksifQ.UFSHd9l0UzpZQwUBUVm1K07mxyJd2fx7iY9H0UJHFewY5YULVOxxHCLDS7cRptTiZoFBTeMM94atr8Fxoox4Wo6jGq-9KNu8lhnV8lNwzrSWbL1OUDhnGtEtZDP0Ey0yAZ7zjZRLB5-eJYXJLQvGG2-He3RCvrCsJQQ0Ak3nJCsGljkKoHDAgoXjmEYE4fFyohXZn7_vHg_xU0RyyvN1K0VsiUZw7kK3TV0tpdGcT7vjZxdVMZFyNJNw63xp-aFd_iyMOeAHZx45S-WhlhQJiiAM7CrqL6z5Ssmw6-430vtgyjvOGvaz4C3D7yht07__UpZ6z4DqKW-CtqmR11pCMg

{
  "text": "hola mundo"
}

###

GET http://localhost:8000/auth0/public/